[env:m5stack-atom]
platform = espressif32
board = m5stack-atom
framework = arduino
monitor_speed = 115200
board_build.partitions = partitions_ota.csv
upload_speed = 921600

build_flags =
    -DCORE_DEBUG_LEVEL=0
    -Wno-deprecated-declarations

lib_deps =
    bogde/HX711@0.7.5
    m5stack/M5Atom@0.1.0
    fastled/FastLED@3.10.3
    ayushsharma82/ElegantOTA@3.1.5
