[env:m5stack-atom]
platform = espressif32
board = m5stack-atom
framework = arduino
monitor_speed = 115200
board_build.partitions = partitions_ota.csv

lib_deps =
    bogde/HX711@0.7.5
    m5stack/M5Atom@0.1.0
    fastled/FastLED@3.6.0
    ayushsharma82/ElegantOTA@3.1.5