name: On PR
permissions:
  contents: 'read'
on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  python-version: 3.11
jobs:

  run-checks:
    uses: ./.github/workflows/run-checks.yml
    secrets: inherit
